name: Generate Snake

on:
  push:
    branches:
      - master  # Ou a branch principal do seu repositório
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/github-snake.svg

      - name: Push the generated snake
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist
